"""Regenerate config/firmware_allowlist.yaml from official GitHub release tags.

The firmware reports a short git revision on its `version` line; for an official
release that revision is an abbreviation of the *tag commit* in the firmware
repository. This script resolves each stable release tag to its full commit SHA
(via the GitHub tags API, which already includes the commit sha — no per-tag
request needed) and writes them as the approved hashes.

Usage:
    python scripts/update_allowlist.py [--min-btfl 4.0.0] [--min-inav 5.0.0]

Set GITHUB_TOKEN in the environment to raise the API rate limit.
"""

from __future__ import annotations

import argparse
import os
import re
from pathlib import Path

import httpx

_SEMVER = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")  # stable releases only (no -RC)

_REPOS = {
    "BTFL": "betaflight/betaflight",
    "INAV": "iNavFlight/inav",
}


def _version_tuple(name: str) -> tuple[int, int, int] | None:
    m = _SEMVER.match(name)
    return (int(m[1]), int(m[2]), int(m[3])) if m else None


def fetch_tags(repo: str, token: str | None, pages: int = 4) -> list[tuple[str, str]]:
    """Return [(tag_name, commit_sha), ...] for a repo across the first pages."""
    headers = {"Accept": "application/vnd.github+json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    out: list[tuple[str, str]] = []
    with httpx.Client(timeout=15, headers=headers) as client:
        for page in range(1, pages + 1):
            r = client.get(
                f"https://api.github.com/repos/{repo}/tags",
                params={"per_page": 100, "page": page},
            )
            r.raise_for_status()
            batch = r.json()
            if not batch:
                break
            for tag in batch:
                out.append((tag["name"], tag["commit"]["sha"]))
    return out


def build_section(repo: str, token: str | None, minimum: tuple[int, int, int]) -> dict[str, list[str]]:
    section: dict[tuple[int, int, int], tuple[str, str]] = {}
    for name, sha in fetch_tags(repo, token):
        vt = _version_tuple(name)
        if vt and vt >= minimum:
            section[vt] = (name, sha)
    # Sort newest first for readability.
    return {section[v][0]: [section[v][1]] for v in sorted(section, reverse=True)}


def render_yaml(sections: dict[str, dict[str, list[str]]]) -> str:
    lines = [
        "# Approved firmware git hashes, keyed by FC variant and version.",
        "#",
        "# Auto-generated by scripts/update_allowlist.py from official release tags.",
        "# Each value is the full tag commit SHA; the firmware reports an abbreviation",
        "# of it, which drone-check matches by prefix. Add manual entries freely.",
        "",
    ]
    for variant in ("BTFL", "INAV", "EMUF"):
        section = sections.get(variant, {})
        if not section:
            lines.append(f"{variant}: {{}}")
            continue
        lines.append(f"{variant}:")
        for version, hashes in section.items():
            lines.append(f'  "{version}":')
            for h in hashes:
                lines.append(f'    - "{h}"')
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-btfl", default="4.0.0")
    parser.add_argument("--min-inav", default="5.0.0")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "config" / "firmware_allowlist.yaml",
    )
    args = parser.parse_args()
    token = os.environ.get("GITHUB_TOKEN")

    minimums = {
        "BTFL": _version_tuple(args.min_btfl) or (4, 0, 0),
        "INAV": _version_tuple(args.min_inav) or (5, 0, 0),
    }
    sections: dict[str, dict[str, list[str]]] = {}
    for variant, repo in _REPOS.items():
        print(f"Fetching {repo} ...")
        sections[variant] = build_section(repo, token, minimums[variant])
        print(f"  {len(sections[variant])} stable releases")

    args.out.write_text(render_yaml(sections), encoding="utf-8")
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
